# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-12 04:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('body_html', models.TextField(blank=True, editable=False, null=True)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_caption', models.CharField(max_length=200)),
                ('image_description', models.TextField(blank=True, null=True)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('display_description', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('prerequisite', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('syllabus', models.FileField(null=True, upload_to='course_uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body_markdown', models.TextField()),
                ('body_html', models.TextField(editable=False)),
                ('description', models.CharField(max_length=140)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2017, 9, 12, 5, 49, 36, 388219, tzinfo=utc))),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('full_day', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_img', models.ImageField(blank=True, null=True, upload_to='avatar_images/')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('contact_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[(1, 'Current Team'), (2, 'Current Students'), (3, 'Collaborators'), (4, 'Visitors'), (5, 'Old Members')], default=1, max_length=1)),
                ('profile_page_markdown', models.TextField(blank=True, null=True)),
                ('profile_page_html', models.TextField(blank=True, editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('published_in', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_publication', models.CharField(blank=True, max_length=4, null=True)),
                ('month_of_publication', models.CharField(blank=True, max_length=10, null=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('project_url', models.CharField(blank=True, max_length=200, null=True)),
                ('pdf', models.FileField(null=True, upload_to='publication_uploads/')),
                ('abstract', models.TextField(blank=True, null=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body_markdown', models.TextField()),
                ('body_html', models.TextField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('website_position_id', models.SlugField(max_length=100, unique=True)),
                ('section_type', models.CharField(choices=[('fixed', 'Fixed Section'), ('page', 'Page')], default='page', max_length=100)),
                ('show_in_nav', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('view_section', 'Can see available sections'), ('edit_section', 'Can edit available sections')),
            },
        ),
    ]
