# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161229_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_page_html',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_page_markdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
