# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20161230_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_html',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
